//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.NguoiThues = new HashSet<NguoiThue>();
        }
    
        public int MaDatPhong { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MaPhong { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string DichVu { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiThue> NguoiThues { get; set; }
    }
}
