//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string MaNguoiThue { get; set; }
        public string MaPhong { get; set; }
        public string MaCTHD { get; set; }
        public Nullable<System.DateTime> NgayTaoHD { get; set; }
        public Nullable<int> TongChiPhi { get; set; }
    
        public virtual ChitietHoaDon ChitietHoaDon { get; set; }
        public virtual NguoiThue NguoiThue { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
