//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiThue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiThue()
        {
            this.ChitietHoaDons = new HashSet<ChitietHoaDon>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaNguoiThue { get; set; }
        public Nullable<int> MaDatPhong { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string SoDienThoai { get; set; }
        public string CMND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHoaDon> ChitietHoaDons { get; set; }
        public virtual DatPhong DatPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
